### ISSUE TITLE
Der Pfad "C:\WebDriver.dll" kann nicht gefunden werden?

### ISSUE THREAD

**Issue by HerrRuin** [senshi-x/ComdirectPostboxDownloader#1]
PS C:\Users\stephan\Documents\ComdirectPostboxDownloader> C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1
Add-Type : Der Parameter "Path" kann nicht an das Ziel gebunden werden. Ausnahme beim Festlegen von "Path": "Der Pfad "C:\WebDriver.dll" kann nicht gefunden werden, da er nicht vorhanden ist."
Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:4 Zeichen:15
+ Add-Type -Path <<<<  "$PSScriptRoot\WebDriver.dll" # Adding Selenium's .NET assembly (dll) to access it's classes in this PowerShell session
    + CategoryInfo          : WriteError: (Smiley (fröhlich) [Add-Type], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : Der Parameter "Path" kann nicht an das Ziel gebunden werden. Ausnahme beim Festlegen von "Path": "Der Pfad "C:\WebDriver.Support.dll" kann nicht gefunden werden, da er nicht vorhanden ist."
Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:5 Zeichen:15
+ Add-Type -Path <<<<  "$PSScriptRoot\WebDriver.Support.dll" # Adding Selenium's .NET assembly (dll) to access it's classes in this PowerShell session
    + CategoryInfo          : WriteError: (Smiley (fröhlich) [Add-Type], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand

....

**Comment by WGPSenshi** [comment]
Steht ja ganz oben: der Pfad zu den .dll wird nicht richtig gefunden. Entweder nicht alles richtig entpackt, oder das Tool wird nicht richtig aus dem verzeichnis heraus aufgerufen.

**Comment by HerrRuin** [comment]
Hallo, Danke für Ihre Antwort.

Wenn ich die WebDriver.dll nach C:\ kopiere, kommt diese Fehlermeldung:


Add-Type : Die Datei oder Assembly "file:///C:\WebDriver.dll" oder eine
> Abhängigkeit davon wurde nicht gefunden. *Die Assembly wird von einer
> Laufzeit erstellt, die aktueller als die derzeit geladene Laufzeit ist, und
> kann nicht geladen werden.*
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:4
> Zeichen:9
> + Add-Type <<<<  -Path "$PSScriptRoot\WebDriver.dll" # Adding Selenium's
> .NET assembly (dll) to access it's classes in this PowerShell session
>     + CategoryInfo          : NotSpecified: (:) [Add-Type],
> BadImageFormatExce
>    ption
>     + FullyQualifiedErrorId :
> System.BadImageFormatException,Microsoft.PowerSh
>    ell.Commands.AddTypeCommand
> Add-Type : Die Datei oder Assembly "file:///C:\WebDriver.Support.dll" oder
> eine Abhängigkeit davon wurde nicht gefunden. Die Assembly wird von einer
> Laufzeit erstellt, die aktueller als die derzeit geladene Laufzeit ist, und
> kann nicht geladen werden.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:5
> Zeichen:9
> + Add-Type <<<<  -Path "$PSScriptRoot\WebDriver.Support.dll" # Adding
> Selenium'
> s .NET assembly (dll) to access it's classes in this PowerShell session
>     + CategoryInfo          : NotSpecified: (:) [Add-Type],
> BadImageFormatExce
>    ption
>     + FullyQualifiedErrorId :
> System.BadImageFormatException,Microsoft.PowerSh
>    ell.Commands.AddTypeCommand
> New-Object : Der Typ [OpenQA.Selenium.Chrome.ChromeDriver] kann nicht
> gefundenwerden. Stellen Sie sicher, dass die Assembly, die diesen Typ
> enthält, geladen wird.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:6
> Zeiche
> n:27
> + $ChromeDriver = New-Object <<<<  OpenQA.Selenium.Chrome.ChromeDriver #
> Creates an instance of this class to control Selenium and stores it in an
> easy to han
> dle variable
>     + CategoryInfo          : InvalidType: (:) [New-Object],
> PSArgumentExcepti
>    on
>     + FullyQualifiedErrorId :
> TypeNotFound,Microsoft.PowerShell.Commands.NewOb
>    jectCommand
> Get-Content : Der Pfad "C:\settings.ini" kann nicht gefunden werden, da er
> nicht vorhanden ist.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:11
> Zeichen:24
> + $settings = Get-Content <<<<  $PSScriptRoot\settings.ini |
> ConvertFrom-String
> Data
>     + CategoryInfo          : ObjectNotFound: (C:\settings.ini:String)
> [Get-Co
>    ntent], ItemNotFoundException
>     + FullyQualifiedErrorId :
> PathNotFound,Microsoft.PowerShell.Commands.GetCo
>    ntentCommand
> New-Item : Der Pfad hat ein ungültiges Format.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:20
> Zeich
> en:9
> + New-Item <<<<  -Force -ItemType directory -Path $postBoxDir | Out-Null
>     + CategoryInfo          : InvalidArgument: (C:\:String) [New-Item],
> Argume
>    ntException
>     + FullyQualifiedErrorId :
> CreateDirectoryArgumentError,Microsoft.PowerShel
>    l.Commands.NewItemCommand
> Sie können keine Methode für einen Ausdruck mit dem Wert NULL aufrufen.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:26
> Zeich
> en:23
> + $ChromeDriver.Navigate <<<< ().GoToURL($comdirectURL)
>     + CategoryInfo          : InvalidOperation: (Navigate:String) [],
> RuntimeE
>    xception
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> Sie können keine Methode für einen Ausdruck mit dem Wert NULL aufrufen.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:29
> Zeich
> en:32
> + $ChromeDriver.FindElementByName <<<< ("param1").SendKeys($settings.user)
>     + CategoryInfo          : InvalidOperation: (FindElementByName:String)
> [],
>     RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> Sie können keine Methode für einen Ausdruck mit dem Wert NULL aufrufen.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:30
> Zeich
> en:32
> + $ChromeDriver.FindElementByName <<<< ("param3").SendKeys($settings.pass)
>     + CategoryInfo          : InvalidOperation: (FindElementByName:String)
> [],
>     RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> Sie können keine Methode für einen Ausdruck mit dem Wert NULL aufrufen.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:31
> Zeich
> en:30
> + $ChromeDriver.FindElementById <<<< ("loginAction").Click()
>     + CategoryInfo          : InvalidOperation: (FindElementById:String)
> [], R
>    untimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> Sie können keine Methode für einen Ausdruck mit dem Wert NULL aufrufen.
> Bei C:\Users\stephan\Documents\ComdirectPostboxDownloader\Download.ps1:34
> Zeich
> en:23
> + $ChromeDriver.Navigate <<<< ().GoToUrl("
> https://kunde.comdirect.de/itx/postei
> ngangsuche")
>     + CategoryInfo          : InvalidOperation: (Navigate:String) [],
> RuntimeE
>    xception
>     + FullyQualifiedErrorId : InvokeMethodOnNull
>

**Comment by WGPSenshi** [comment]
Vermutlich nutzen Sie noch ein altes Powershell (Version kleiner 3.0), dort wird das Skript nicht unterstützt.

**Comment by HerrRuin** [comment]
Besten Dank WGPSenshi !

Ich hatte noch Version 2.0 und habe jetzt auf 5.1 geupdated. Nachdem ich noch den aktuellen chromedriver.exe für Chrome 83 herunter geladen hatte ging es.

Jetzt habe ich Fragen zur Benutzung.

Wir kann ich Dokumente aus dem Archiv laden? 
Er zeigt nur die Postbox an und dort nur 2020 und 2019. 
Wie kann ich ins Archiv wechseln und die Auswahlliste aktualisieren?

Und wie kann ich ihm sagen, dass er nur Finanzreports runter laden soll und nicht alle Dokumente?
Gibt es da auch eine Auswahl?

Danke nochmals für den Tipp mit der Powershell Version!
VG Stephan

**Comment by retiredHero** [comment]
Hallo HerrRuin,

ich habe gleich eine etwas bissige Frage: Haben Sie die Readme gelesen?

Nehmen Sie sich die [settings.ini.example](https://github.com/WGPSenshi/ComdirectPostboxDownloader/blob/master/settings.ini.example) als Beispiel.


Wie kann man Dokumente aus dem Archiv laden:
in die settings.ini gehen und den Parameter downloadOnlyFromOnlineArchive auf true setzen
Readme-Ausschnitt:
downloadOnlyFromOnlineArchive = Lädt nur Dateien aus dem Postbox-Archiv herunter.

Wie kann ich nur Finanzreports runter laden:
in die settings.ini gehen und den Parameter downloadOnlyFilenames auf "true" setzen
in die settings.ini gehen und dem Parameter downloadOnlyFilenamesArray zum Beispiel "Finanzreport" hinzufügen..
also downloadOnlyFilenamesArray = ["Finanzreport"]

Readme-Ausschnitt:
downloadOnlyFilenames = Lädt nur Dateien herunter, deren Dateiname mit einem der hier angegeben Wörter beginnt. Bei False wird alles heruntergeladen.
downloadOnlyFilenamesArray = Liste der gewünschten Dateinamen

**Comment by senshi-x** [comment]
Keine Reaktion mehr des Issue-Erstellers, deshalb zu.
