### ISSUE TITLE
Multiuser / settings.ini support

### ISSUE THREAD

**Issue by MrFr33man123** [senshi-x/ComdirectPostboxDownloader#19]
To use the downloader with more people frome one household.

Is it possible to ask für the pin at runtime and have multiple settings that can be choosen from?

**Comment by senshi-x** [comment]
Pull Requests are welcome :) . Definitely not a priority feature for me, though it should be fairly easy to implement.

For now, you can simply replace the settings.ini as needed, or even write a small script to choose the correct settings based on your input.
