### ISSUE TITLE
Nachrichten mit "Wichtig:" am Anfang lösen auf Windows einen Fehler aus

### ISSUE THREAD

**Issue by tomkoenecke** [senshi-x/ComdirectPostboxDownloader#20]
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Users\\...\\Zielordner\\Wichtig:'

downloadOnlyFilenames ist auf False.
Geht hier wahrscheinlich um den Doppelpunkt nach Wichtig, oder?

**Comment by senshi-x** [comment]
Klappt bei mir problemlos, hatte gerade auch ein "Wichtig:"-Dokument. Das ":" wird einfach entfernt.

Welches Python, welches Windows?
Für das "Säubern" der Filenames wird das path_validate-Modul genutzt, welches OS-spezifisch säubern sollte.

**Comment by tomkoenecke** [comment]
Python 3.9.1, Windows 10

Ich schaue mir es heute Abend noch einmal an, danke!

**Comment by tomkoenecke** [comment]
Ah, das Problem entsteht wenn useSubFolders gewählt ist (und der "Wichtig"-Ordner noch nicht erzeugt wurde?).
Das os.makedirs() in Zeile 343 kriegt einen nicht gesäuberten foldername, oder?

**Comment by senshi-x** [comment]
Ah, subfolder nutze ich nie, deshalb konnte ich es nicht reproduzieren :) . Aber deine Vermutung klingt sehr richtig, sollte ein leichter Fix sein. Ich mach mich gleich dran.
