### ISSUE TITLE
Nutzung Tool

### ISSUE THREAD

**Issue by Phillipp93** [senshi-x/ComdirectPostboxDownloader#21]
Hi zusammen, 

ich bekomm das mit den Tool nicht hin.
Ich habe Python 3.9 runtergeladen und die settings.ini Datei konfiguriert. 

Was ist mit "pip -r requirments.txt" gemeint und in welchem Verzeichnis führe ich das aus?

Kann mir hier einer helfen? 

vielen Dank im Voraus. 
Phillipp

**Comment by tomkoenecke** [comment]
Das führst du direkt in dem geklonten Verzeichnis aus, also dort wo auch die requirements.txt liegt.

`pip install -r requirements.txt`

Pip ist der Python Package Manager, der die für diesen Code hier benötigten Pakete deinem Python hinzufügt. 
Sollte pip nicht funktionieren, lief irgendwas bei der Installation von Python nicht richtig, kannste dann mal googeln.

Und dann im gleichen Verzeichnis (wo auch die main.py liegt, einfach `python main.py` ausführen. 

Meld dich wenn's irgendwo noch hackt!

**Comment by Phillipp93** [comment]
Hi Tom,
danke für die schnelle Rückmeldung. 

Ich habe mir die Dateien runtergeladen:
![image](https://user-images.githubusercontent.com/97559142/149207360-2d2d6a90-7c4d-47e2-a4d6-9c9aed8bcdf7.png)

Dort liegt jetzt die Datei "requirements.txt" Datei drin. Wie führe ich das dann aus? Über die Python Konsole bekomme ich eine Fehlermeldung.

**Comment by senshi-x** [comment]
Wenn du pip nicht direkt aufrufen kannst, wonach es aussieht, probier mal `python -m pip install -r requirements.txt` in der Kommandozeile/Eingabeaufforderung.

**Comment by Phillipp93** [comment]
Vielen Dank, Ihr habt mir schon sehr helfen können. 
Ich habe das mit dem Programm soweit hinbekommen. 

Jetzt habe ich noch ein Problem bei de settings.ini Datei 

"C:\Users\Benutzer\Desktop\ComdirectPostboxDownloader-master>python main.py
loading settings...
please provide settings.ini to start program.
Press ENTER to close. Create settings.ini from the example before trying again."

ich hatte die Beispieldatei angepasst und auch zusätzlich ein neues Txt-dokument erstellt, da es nicht funktionirt hatte. 
Das hat leider nichts gebracht. wo liegt hier mein Fehler?

**Comment by retiredHero** [comment]
1) Die Fehlermeldung sagt aus, dass die "settings.ini" nicht gefunden und somit nicht geladen werden konnte...

2) liegt die settings.ini-Datei noch im gleichen Verzeichnis?
->also hier: C:\Users\Benutzer\Desktop\ComdirectPostboxDownloader-master\settings.ini

3) was heißt, du hast ein neues Txt-Dokument erstellt?


ich bitte um einen erneuten Screenshot deines Ordners mit allen Dokumenten.
Und den Inhalt deiner Settings.ini - ohne die api- und login-Informationen! Bitte diese vor Upload unkenntlich machen.

**Comment by Phillipp93** [comment]
2. ja die liegt noch im gleichen Verzeichnis.
![image](https://user-images.githubusercontent.com/97559142/150638340-68dc42fa-925b-4bac-aa4d-9bd31ce36f67.png)

3. vergiss das einfach

![image](https://user-images.githubusercontent.com/97559142/150638392-f08a1e06-3fb2-4f31-b29c-ef3e76f4c22c.png)

**Comment by retiredHero** [comment]
die Datei sieht auf die schnelle okay aus, aber

ich glaube bei 3.) liegt der Hund begraben... du hast zwar ein neues "txt"-Dokument erstellt, aber das Dokument nicht als .ini-Datei abgespeichert?

Bei dir steht bei der settings-Datei noch "EXAMPLE-Datei", d.h. du hast die Endung noch nicht geändert zu einer .ini-Datei... dann würde dort irgendwas von "Konfigurationsdatei" o.ä. stehen.. 

Du kannst das überprüfen, wenn du einen Rechtsklick auf deine "settings.ini"-Datei machst und dort dir die Einstellungen anschaust, dann steht doch bei "Dateityp" sicherlich noch EXMAPLE und nicht .ini

Soo.. wie ändert man das: 
- Am einfachsten gehst du in deine Explorer-Einstellungen und zeigst dir die Endungen aller bekannten Dateitypen auch an:
![image](https://user-images.githubusercontent.com/12251507/150638562-f4153d12-8870-4c05-949b-9d80bfd32c94.png)

- danach dann einfach deine Datei "settings.ini.example" umbenennen zu "settings.ini" und bestätigen, dass du den Datentyp auch ändern möchtest.

und dann sollte es funktionieren.

**Comment by Phillipp93** [comment]
Perfekt, jetzt hat es geklappt und bin im Programm drin.

Viel Dank an alle für die Unterstützung!

**Comment by senshi-x** [comment]
Freut mich, dass es nun geklappt hat! Danke auch an alle für die Unterstützung! Wenn noch mehr Fragen/Probleme aufkommen, einfach ein neues Issue aufmachen :) .
