### ISSUE TITLE
Probleme mit doppelten Anführungszeichen

### ISSUE THREAD

**Issue by BBMBB** [senshi-x/ComdirectPostboxDownloader#32]
Erstmal vielen Dank für das super Projekt!

Hat mir schon viel geholfen!

Auf meinem Linux Mint System bekomme ich Probleme mit doppelten Anführungszeichen:

`File "main.py", line 247
    printLeftString = f"{str(idx):>5} | [cyan]{document.dateCreation.strftime("%Y-%m-%d")}[/cyan] | {sanitize_filename(document.name)}"
                                                                               ^
SyntaxError: f-string: unmatched '('`

**Comment by senshi-x** [comment]
Ich vermute, du nutzt noch eine ältere Python-Version. GEnau das Problem von Doublequotes innerhalb eines f-Strings wurde erst mit Python 3.12 behoben.

Danke dir aber noch viel mehr für den PR, der das Problem ohne Nebenwirkungen fixt. :)
