### ISSUE TITLE
Zweites Konto im selben Zugang ebenfalls abfragen?

### ISSUE THREAD

**Issue by Helmi** [senshi-x/ComdirectPostboxDownloader#8]
Hi,

irgend eine Idee wie das zweite Konto, das über den selben Zugang wie das erste erreichbar ist ebenfalls abrufbar wäre? Es existieren leider getrennte Nachrichtenpostfächer für beide Konten, das Script scheint nur das erste abzufragen.

Danke!

**Comment by retiredHero** [comment]
Hi, 
das ist mit der aktuellen Version des Scripts nicht möglich. 
Idee: Die URL zum Abrufen der Dokumente anpassen: Zeile 253 in der Datei main.py.
Oder nochmals die Schnittstellendokumentation der comdirect durchlesen und nach dem "zweiten Konto" suchen bzw. nach der Möglichkeit alle vorhandenen Nachrichtenpostfächer für den Zugang auszulesen und danach die URL/Parameter so anzupassen, wie sie benötigt wird... 

Da ich bislang nur ein Konto hinter meinem Zugang habe, war das bislang kein Thema für mich.. 
Viel Erfolg!

**Comment by wondering639** [comment]
Hatte das gleiche Problem. Bei mir war das zweite ein Gemeinschaftskonto, habe dann den Login der 2. Person genutzt, da diese nur das Gemeinschaftskonto hatte. Das nur als mögliche Idee, je nach Konstellation.

**Comment by Speedylux** [comment]
Der API-Key ist kundenspeziefisch. D.h. für alle Kontoverbindungen, bei denen du nohrmalerweise im Browser ohne zusätzliche Anmeldung wechseln kannst, gehört der gleiche API-Key (ClientID / Client secret)

Es ist jedoch eine neue Anmeldung mit Zugangsnummer und PIN für jede weitere Kundennummer notwendig, um die Postbox Dokumente herunterzuladen.

Viele Grüße!

**Comment by senshi-x** [comment]
Ist aktuell nicht unterstützt und nicht von mir geplant. Wäre technisch sicher machbar, Pull Requests dafür sind willkommen :) .
